;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-star
        delete-window
        electric-newline-and-maybe-indent
        helm-M-x
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        swiper-mc
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        c-electric-paren
        end-of-buffer
        ivy-switch-buffer
        kill-region
        magit-next-line
        omnisharp-add-dot-and-auto-complete
        yaml-electric-backspace
        ))
