;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        delete-window
        electric-newline-and-maybe-indent
        helm-M-x
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        kill-region
        yaml-electric-backspace
        ))
